### ISSUE TITLE
No module named flask

### ISSUE THREAD

**Issue by srcole** [shantnu/PythonForHackers#1]
Hi, I am using this repository as in the beginning of your book, but when I run the command `./app.py &`, I get an error `ImportError: No module named 'flask'`.

I tried simply to pip install flask, but I got a Permission Denied error. Or even when I do `sudo pip install flask`, it looks to install correctly, but I am still getting that ImportError.

**Comment by shantnu** [comment]
Ok, found out what the problem was.

Some of the libraries have "vanished", which means pip can't install everything. Which is weird, as authors shouldn't remove old versions.

Anyway, I've updated the requirements file, though I dont know if this will have an effect on anything else.

Anyway, I've done an update. You'll have to do:

vagrant up --provision

to force it to install everything again.

PS: Im surprised you're the only one who noticed the problem; it means you're te only one who ran the code! Well done.

I'll leave this bug open in case you find more problems.

**Comment by srcole** [comment]
Thanks for the quick response!

I ran `vagrant up --provision` in the directory that I had all the files in, and it seemed to reinstall everything. But I'm still getting an error

`vagrant@vagrant-ubuntu-trusty-32:/vagrant$ ./app.py &`

[1] 2002
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ Traceback (most recent call last):
  File "./app.py", line 3, in <module>
    from flask import *
ImportError: No module named 'flask'

**Comment by shantnu** [comment]
Did you do a _**git pull**_ to get the latest changes?

If so, do you mind running (within vagrant):

 _sudo pip3 install -r /vagrant/requirements.txt_

If you see any error messages, post them here.

**Comment by srcole** [comment]
Cool, now I no longer get the importerror for flask. But when I try running the same command as above, I get this error:

[1] 2905
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ -bash: ./app.py: Permission denied

**Comment by shantnu** [comment]
Try python app.py

**Comment by srcole** [comment]
cool! I can get the website to work and logged in with Perry.Platypus.

But `python app.py &` doesn't let me keep running commands.
